### ISSUE TITLE
検索のOR条件を繰り返し処理で追加したい

### ISSUE THREAD

**Issue by juv-shun** [juv-shun/alerm_estimated_charge#1]
[https://github.com/juv-shun/alerm_estimated_charge/blob/master/lambda_function.py#L103](url) 
`return df.loc[(df['Diff(1m)'] > THRESHOLD) | (df['Diff(3m)'] > THRESHOLD)]`について、
現状1mと3mの箇所を直書きしているが`REL_MONTH`から動的にORを追加して条件指定できるようにしたい。

**Comment by unacowa** [comment]
このケースは、畳み込みにあたると思います。(list -> value) 
http://d.hatena.ne.jp/blanketsky/20071129/1196329379

処理的には、例えば演算子が、 + の場合上記の例にあるように、

```
# 仮想的な言語
reduce(+, [1, 2, 3, 4])
=> (1 + (2 + (3 + (4))))
=> 10

reduce(or, [false, false, true])
=> (false or (false or (true)))
=> true
```
python の場合、`operator` モジュールに、 `or` があります。
また、ジェネレータ内包表記があります。
http://qiita.com/ycctw1443/items/4da894971630810379c0#%E3%82%B8%E3%82%A7%E3%83%8D%E3%83%AC%E3%83%BC%E3%82%BF%E5%BC%8F

* ジェネレータ内包表記
* `operator.or`

を用いて、表現できると思います。(試していません)

**Comment by juv-shun** [comment]
ジェネレータ内包表記ではなく、リスト内包表記を利用しましたが、実装できました。
